### ISSUE TITLE
countries_with_no_deaths_count(): Złe przykłady

### ISSUE THREAD

**Issue by skalermo** [korona-science/homework-skalermo#1]
Funkcja przechodzi testy, choć nie powinna, bo dla
`countries_with_no_deaths_count(datetime.date(2020, 3, 15))`
zwraca 171, a wg przykładu powinno być 44.

**Comment by RouNNdeL** [comment]
Gdzie mamy przekazywać informacje z żebyście je czytali?

![SmartSelect_20200319-094908_Slack](https://user-images.githubusercontent.com/22538735/77048587-fe5a6700-69c6-11ea-9c68-a04c1336785f.jpg)

![SmartSelect_20200319-094946_Facebook](https://user-images.githubusercontent.com/22538735/77048642-0ca88300-69c7-11ea-8189-e5ce32c596db.jpg)
